# Pandas 入门

pandas经常和其它工具一同使用，如数值计算工具NumPy和SciPy，分析库statsmodels和scikit-learn，和数据可视化库matplotlib。pandas是基于NumPy数组构建的，特别是基于数组的函数和不使用for循环的数据处理。

**虽然pandas采用了大量的NumPy编码风格，但二者最大的不同是pandas是专门为处理表格和混杂数据设计的。而NumPy更适合处理统一的数值数组数据。**

In [3]:
import numpy as np
import pandas as pd

## Pandas数据结构

- Series：一维数组对象，它由一组数据（各种NumPy数据类型）以及一组**与之相zip的数据标签（即索引）**组成。
- DataFrame：表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）。**DataFrame既有行索引也有列索引，它可以被看做由Series组成的字典（共用同一个索引）。**DataFrame中的数据是以一个或多个二维块存放的（而不是列表、字典或别的一维数据结构）。

### Series

In [83]:
obj = pd.Series([4, 7, -5, 3])
obj  # 索引在左，值在右

0    4
1    7
2   -5
3    3
dtype: int64

In [84]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [85]:
obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [86]:
# 指定索引
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'c', 'a'])
obj2.index

Index(['d', 'b', 'c', 'a'], dtype='object')

In [87]:
obj2[['b', 'c']]  # 通过索引选取值

b    7
c   -5
dtype: int64

In [88]:
obj2[obj2 > 0]

d    4
b    7
a    3
dtype: int64

In [89]:
obj2 * 2
np.exp(obj2)

d      54.598150
b    1096.633158
c       0.006738
a      20.085537
dtype: float64

In [90]:
# 由字典创建Series
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

# 如果只传入一个字典，
# 则Series中的索引就是原字典的键（有序排列）。

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [91]:
# 可以传入排好序的字典key，以改变顺序
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

# 由于"California"所对应的sdata值找不到，
# 所以其结果就为NaN（即“非数字”（not a number），在pandas中，它用于表示缺失或NA值）。
# 因为‘Utah’不在states中，它被从结果中除去。

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [92]:
# 检测缺失数据
# isnull() 函数
pd.isnull(obj4)

# notnull() 函数
pd.notnull(obj4)

# Series也有类似的实例方法
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

对于许多应用而言，Series最重要的一个功能是，它会根据运算的索引标签自动对齐数据：

In [114]:
# 数据自动对齐功能（类似 join）
print(obj3)
print(obj4)
obj3 + obj4

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [94]:
# name 属性
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [95]:
# Series的索引可以通过赋值的方式就地修改
print(obj)  # 默认的索引是 0-N
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

0    4
1    7
2   -5
3    3
dtype: int64


Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

虽然DataFrame是以二维结构保存数据的，但仍然可以轻松地将其表示为更高维度的数据（层次化索引的表格型结构，这是pandas中许多高级数据处理功能的关键要素，我们会在第8章讨论这个问题）。

DataFrame构造函数所能接受的各种数据：
![](Img/7178691-106835b28c0cea5a.png))

#### 创建方式

##### 创建方式1:传入由等长列表或NumPy数组组成的字典

In [96]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)  # 会自动加上索引
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [97]:
# 指定顺序排列
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [98]:
# 如果传入的列在数据中找不到，会在结果中产生缺失值

frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2  # debt:NaN
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [99]:
# 获取column
frame2['state']
frame2.year  # 这么写要column name中没空格

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [100]:
# 获取row
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [101]:
# 通过赋值，修改column
frame2.debt = 16.5
frame2

frame2.debt = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

将列表或数组赋值给某个列时，其长度必须跟DataFrame的长度相匹配。
如果赋值的是一个Series，就会精确匹配DataFrame的索引，所有的空位都将被填上缺失值：

In [102]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2.debt = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [103]:
# 关键字 del 用于删除column
# 先添加布尔值的列
frame2['eastern'] = frame2.state == 'Ohio'  # 不能用 frame2.eastern 创建新列
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [104]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

> 注意：通过索引方式返回的列只是相应数据的视图而已，并不是副本。因此，对返回的Series所做的任何就地修改全都会反映到源DataFrame上。通过Series的copy方法即可指定复制列。

##### 创建方式2：嵌套字典

In [7]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [8]:
# 默认情况下，传入嵌套字典会解释成什么？
frame3 = pd.DataFrame(pop)
frame3

# 外层字典的键作为columns，内层键则作为index。

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [107]:
# 转置
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [108]:
# 明确索引
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [109]:
# 由Series组成的字典
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [110]:
# 设置 DataFrame 的 index 和 columns 的 name 属性
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3.values  # values 二维 ndarray

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [111]:
frame2.values  # type=object会选用兼容所有数据类型

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象

**pandas的索引对象负责管理轴标签和其他元数据（比如轴名称等）。**

构建Series或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个Index。

![](Img/7178691-5499d14f0e2cd639.jpg)


In [9]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index
index[1:]

Index(['b', 'c'], dtype='object')

In [10]:
# index 为不可变对象，用户不能对其修改
index[1] = 'd'  # TypeError

TypeError: Index does not support mutable operations

In [11]:
# 不可变可以使 Index 对象在多个数据结构之间可以安全共享
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2
obj2.index is labels  # True

In [12]:
# Index 类似一个固定大小的集合，
# 但是可以包含重复值,选择重复的标签会显示所有的结果

frame3.columns
'Nevada' in frame3.columns  # True

True

## Pandas 基本功能

关注最重要的功能，更详尽的内容推荐阅读文档。

### 重新索引（reindex）

![](Img/7178691-efa3dbd4b83c61ec.jpg)

In [13]:
# 重新索引（reindex）
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [14]:
# 会按照reindex的顺序重排，如果索引值不存在就引入缺失
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [17]:
# reindex 插值处理
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [18]:
obj3.reindex(range(3), method='ffill')  # forward fill：1 向前 替换为 0 对应的值

0      blue
1      blue
2    purple
dtype: object

借助 DataFrame，`reindex`可以修改（行）索引和列。
- 只传递一个序列时，会重新索引结果的行。
- 列可以用 columns 关键字重新索引。

In [19]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

# 重新索引结果的行
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

# 用 columns 关键字重新索引列
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### 丢弃指定轴上的项

传递索引数组或者列表到`drop` 方法，会返回一个在指定轴上删除了指定值的新对象。

In [3]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [5]:
new_obj = obj.drop(['b', 'c'])
new_obj

a    0.0
d    3.0
e    4.0
dtype: float64

In [10]:
# DataFrame
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=[
                    'Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])
data.drop(['Colorado', 'Ohio'])  # 标签序列调用drop会从行标签(axis=0)删除值

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [11]:
# 删除列的值
data.drop('two', axis=1)  # 指定 axis = 1
data.drop(['two', 'four'], axis='columns')  # 指定 axis = 'columns'

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [15]:
# 就地修改
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 索引、选取和过滤
Series索引的工作方式类似于 NumPy数组的索引，但是Seires的索引值不只是整数。
![](Img/7178691-64354f2ab777bd8c.png)

In [19]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj['b']
obj[1]
obj[2:4]
obj[['b', 'a', 'd']]
obj[[1:3]]
obj[obj < 2]

1.0

In [22]:
# 标签切片
obj['b':'c']  # 包含末端
obj['b':'c'] = 5  # 可以对值进行设置
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [24]:
# 用值或者序列对 DataFrame 索引
data = pd.DataFrame(np.arange(16).reshape(4, 4), index=[
                    'Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])
data['two']
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [ ]:
data[:2]  # 通过切片
data[data['three'] > 5]  # 通过布尔型数组
data[data < 5] = 0  # 布尔型 DataFrame

#### 用 loc 和 iloc 进行选取

- `loc`：轴标签
- `iloc`：整数索引

In [26]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [27]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [28]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [29]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [30]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [31]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [ ]:
# 整数索引

In [33]:
ser = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser
# 为了进行统一，如果轴索引含有整数，
# 数据选取总会使用标签。

a    0.0
b    1.0
c    2.0
dtype: float64

In [ ]:
# 算术运算和数据对齐

Pandas 可以对不同索引的对象进行算术运算，会索引自动对齐。

In [35]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [36]:
s1 + s2  # 自动对齐

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [37]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list(
    'bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list(
    'bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [38]:
df1 + df2  # 会自动对齐到行和列

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [40]:
# DataFrame对象相加，没有共用的列或标签，结果会为空
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### 在算术方法中填充值

![表5-5 灵活的算术方法](Img/7178691-16857a1021f98d1f.png)

在对不同索引的对象进行算术运算时，你可能希望当一个对象中某个轴标签在另一个对象中找不到时填充一个特殊值（比如0）：

In [44]:
df1 = pd.DataFrame(np.arange(12.).reshape(3, 4), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape(4, 5), columns=list('abcde'))

In [45]:
df2.loc[1, 'b'] = np.nan

In [46]:
df1 + df2  # 没有重叠的为 NaN

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [47]:
df1.add(df2, fill_value=0)  # 填充

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [50]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [49]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [52]:
# reindex 也可以指定填充值
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [ ]:
# DataFrame 和 Series之间的运算

In [53]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [54]:
arr[0]

array([0., 1., 2., 3.])

In [55]:
arr - arr[0]  # 广播（broadcasting）：每行都减1

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [57]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [58]:
frame - series
# DataFrame和Series之间的算术运算会将Series的索引匹配到DataFrame的列，
# 然后沿着行一直向下广播

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [59]:
# 如果某个索引值在 DataFrame 的列或者 Series 的索引找不到
# 参与运算的两个对象会被重新索引以形成并集
series2 = pd.Series(range(3), index=list('bef'))
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [60]:
# 匹配行，且在列上广播？
# 匹配DataFrame的行索引（axis='index' or axis=0）并进行广播
series3 = frame['d']
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 函数应用和映射



In [63]:
# 法1:：NumPy 的 ufuncs(元素级数组方法)
frame = pd.DataFrame(np.random.randn(4, 3),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame
np.abs(frame)

b         d         e
Utah    0.873434  0.447831  0.144251
Ohio    1.164062  0.788574  0.228027
Texas   0.845539  0.271924  1.462962
Oregon  1.350731  0.773690  0.963658

In [64]:
# 法2：函数应用到列或者行形成的一维数组上
def f(x): return x.max() - x.min()


frame.apply(f)  # 在每列执行

b    2.224166
d    1.562264
e    1.607213
dtype: float64

In [65]:
frame.apply(f, axis='columns')  # 每行执行

Utah      1.321265
Ohio      0.936035
Texas     1.734885
Oregon    2.124422
dtype: float64

In [66]:
# 传递到apply的函数不是必须返回一个标量，
# 还可以返回由多个值组成的Series：


def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])


frame.apply(f)

b         d         e
min -0.873434 -0.773690 -0.144251
max  1.350731  0.788574  1.462962

In [67]:
# 元素级的Python函数也可以使用
def format(x): return '%.2f' % x


frame.applymap(format)

b      d      e
Utah    -0.87   0.45  -0.14
Ohio     1.16   0.79   0.23
Texas    0.85  -0.27   1.46
Oregon   1.35  -0.77   0.96

In [68]:
frame['e'].map(format)  # Seires 具有应用元素级函数map

Utah      -0.14
Ohio       0.23
Texas      1.46
Oregon     0.96
Name: e, dtype: object

### 排序和排名

![表5-6 排名时用于破坏平级关系的方法](Img/7178691-7edfab5b4a147581.png)


In [70]:
obj = pd.Series(range(4), index=list('dabc'))
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

frame.sort_index()  # row
frame.sort_index(axis=1)  # column

In [71]:
# 降序
frame.sort_index(axis=1, ascending=False)

e         d         b
Utah   -0.144251  0.447831 -0.873434
Ohio    0.228027  0.788574  1.164062
Texas   1.462962 -0.271924  0.845539
Oregon  0.963658 -0.773690  1.350731

In [74]:
# 按值对Series排序，可使用 sort_values 方法
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [75]:
# 排序时，缺失值默认放到Series的末尾
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [76]:
# 多个值排序：传入by 选项
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [77]:
# rank：通过“为各组分配一个平均排名”的方式破坏平级关系
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [78]:
# 根据值在原数据中出现的顺序排名
obj.rank(method='first')  # fisrt show

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [79]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [80]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2],
                      'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

### 带有重复标签的轴索引


In [81]:
# 带有重复标签的index
obj = pd.Series(range(5), index=list('aabbc'))
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [82]:
# 检查标签是否唯一
obj.index.is_unique  # False

False

In [83]:
# 当索引带有重复值时，数据选取则返回一个 Series
# 如果只有一个索引，就返回标量值
obj['a']

# 注意：如存在重复索引，会让输出类型发生变化，增加代码的复杂度。

a    0
a    1
dtype: int64

In [84]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df.loc['b']  # 行存在重复索引也是同样

0         1         2
b -0.400808  0.431019  1.007096
b -0.540132 -0.921321  0.448212

## 汇总和计算描述统计

pandas对象拥有一组常用的数学和统计方法。它们大部分都属于约简和汇总统计，用于从Series中提取单个值（如sum或mean）或从DataFrame的行或列中提取一个Series。**跟对应的NumPy数组方法相比，它们都是基于没有缺失数据的假设而构建的。**

![](Img/7178691-11fa967f658ac314.jpg)

In [86]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                  index=list('abcd'),
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [87]:
df.sum()  # 返回一个Series

one    9.25
two   -5.80
dtype: float64

In [91]:
df.sum(axis=1)
# or
df.sum(axis='columns')  # 按行求和

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [92]:
# 进行汇总计算和求和，NAN会自动被排除，除非整个切片都是NAN
# 通过skipna可以禁用该功能
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

约简方法的常用选项：

![](Img/7178691-af35e3809278410e.jpg)

In [94]:
# 间接统计
df.idxmax()  # 达到最大值的索引

one    b
two    d
dtype: object

In [95]:
# 累计统计
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [96]:
# 一次性产生多个汇总统计
df.describe()  # 数值型数据

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [97]:
obj = pd.Series(['a', 'a', 'b', 'c']*4)
obj.describe()  # 非数值型数据，返回的结果不一样

count     16
unique     3
top        a
freq       8
dtype: object

### 相关系数与协方差

```
!pip install pandas-datareader
```

In [ ]:
import pandas_datareader.data as web  # 下载数据
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                      for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                       for ticker, data in all_data.items()})

In [ ]:
# 计算价格的百分数变化
returns = price.pricect_change()
returns, tail()

In [ ]:
# 相关系数
returns['MSFT'].corr(returns['IBM'])

# 计算两个Series中重叠的、非NA的、按索引对齐的值的相关系数

In [ ]:
# 协方差
returns['MSFT'].cov(returns['IBM'])
# or
returns.MSFT.corr(returns.IBM)  # 更简洁的语法

In [ ]:
# DataFrame 的 corrwith 方法：
# 返回和另一个 Series 或 DataFrame 的相关系数
returns.corrwith(returns.IBM)

In [ ]:
returns.corrwith(volume)
# 传入DataFrame会计算按列名配对的相关系数
# 传入 axis = columns 则可以按行计算
# 在计算相关系数之前，所有数据项都会按照标签对齐

## 唯一值、值计算以及成员资格

![表5-9 唯一值、值计数、成员资格方法](Img/7178691-b53c4a9d65a2db32.png)

In [ ]:
# unique() 唯一值

obj = pd.Seires(list['cadaabbcc'])
uniques = obj.unique()  # 得到Series中的唯一值数组

In [2]:
# 返回的数组是未排序的，如果需要排序：
uniques_sort = obj.uniques.sort()

NameError: name 'obj' is not defined

In [4]:
# 计算频率
obj.value_counts()  # m默认降序排列

NameError: name 'obj' is not defined

In [ ]:
# 可用于任何数组或序列
pd.values_counts(obj.values, sort=True)

In [ ]:
# isin()：判断矢量化集合的成员资格
# 可用于过滤 Series 中或 DataFrame 列中数据的子集
obj
mask = obj.isin(['b', 'c'])
mask  # 返回布尔型Series
obj[mask]

In [ ]:
# Index.get_indexer方法
# 可以给你一个索引数组，从可能包含重复值的数组到另一个不同值的数组
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match_match)

In [5]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [6]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0